# mix
t1=(3,5, 6, 64,23,232,54,"rahul","das",True, False)
print("in tuple form ",t1)
t3=list(t1)
print("\nafter converting into list:",t3)
print("\nlength:",len(t1))
t3.append(706)
print("\nafter appending 706:",t3)
t3.remove(54)
print("\nafter removing 54:",t3)
t3.pop(2)
print("\nafter poping 2nd element:",t3)
t3.insert(2,"das")
print("\nafter inserting das:",t3)
t3.extend(["rahul","das"])
print("\nafter extending rahul and das:",t3)
t3.reverse()
print("\nafter reversing:",t3)
t4 =t3.copy()
print(t4)
t2=tuple(t3)
print("\nAfter converting into tuple",t2)

